### ISSUE TITLE
upgrade xunit

### ISSUE THREAD

**Issue by AChehre** [shaynevanasperen/TestStack.BDDfy.Xunit#6]
Hi,
Do we need to upgrade Xunit to a new version?
The XunitTestCase constructor that BDDfy.Xunit is using is deprecated.

**Comment by shaynevanasperen** [comment]
No, we don't need to upgrade Xunit to a new version.

Only the default (no arguments) constructor of `XunitTestCase` is marked as obsolete. We are not calling that overload. We are calling the other overload that has arguments.

**Comment by AChehre** [comment]
```
 /// <summary />
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
    public XunitTestCase() => this.DiagnosticMessageSink = (IMessageSink) new NullMessageSink();

    /// <summary>
    /// Initializes a new instance of the <see cref="T:Xunit.Sdk.XunitTestCase" /> class.
    /// </summary>
    /// <param name="diagnosticMessageSink">The message sink used to send diagnostic messages</param>
    /// <param name="defaultMethodDisplay">Default method display to use (when not customized).</param>
    /// <param name="testMethod">The test method this test case belongs to.</param>
    /// <param name="testMethodArguments">The arguments for the test method.</param>
    [Obsolete("Please call the constructor which takes TestMethodDisplayOptions")]
    public XunitTestCase(
      IMessageSink diagnosticMessageSink,
      TestMethodDisplay defaultMethodDisplay,
      ITestMethod testMethod,
      object[] testMethodArguments = null)
      : this(diagnosticMessageSink, defaultMethodDisplay, TestMethodDisplayOptions.None, testMethod, testMethodArguments)
    {
    }
```
I checked the Xunit package cource and the second one is the constructor that we are calling and it has Obsolete attribute. 
May be Im doing wrong action.

**Comment by shaynevanasperen** [comment]
I see now. You were referring to the source code of the latest version of Xunit. I've [updated to that version now](https://github.com/shaynevanasperen/TestStack.BDDfy.Xunit/pull/8) and fixed the warnings about obsolete code.

Please let me know if you approve of the change.
